export const AUTH_PERMISSIONS = {
  manager: ['MANAGE_STAFF', 'MANAGE_INVENTORY', 'MANAGE_PRESCRIPTIONS', 'VIEW_REPORTS'],
  pharmacist: ['MANAGE_PRESCRIPTIONS', 'VIEW_INVENTORY', 'VIEW_REPORTS'],
  insurance: ['VIEW_CLAIMS', 'MANAGE_CLAIMS'],
  government: ['VIEW_DASHBOARD', 'VIEW_REPORTS', 'VIEW_AUDIT_LOGS'],
  admin: ['MANAGE_USERS', 'MANAGE_PHARMACIES', 'MANAGE_SYSTEM', 'VIEW_AUDIT_LOGS'],
  patient: ['VIEW_PROFILE', 'MANAGE_RESERVATIONS', 'MANAGE_PRESCRIPTIONS'],
};

export const STAFF_ROLE_PERMISSIONS: Record<string, string[]> = {
  MANAGER: AUTH_PERMISSIONS.manager,
  PHARMACIST: AUTH_PERMISSIONS.pharmacist,
  CASHIER: ['VIEW_INVENTORY', 'MANAGE_RESERVATIONS'],
  DELIVERY: ['VIEW_INVENTORY'],
};
